config/routes.rb
Students::Application.routes.draw do
  root to: "students#index"
  resources :students
end

app/models/student.rb
class Student < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  protect_from_forgery
  require 'json'

  def index
    result = Net::HTTP.get(URI.parse('https://crystal-pepsi.herokuapp.com/students'))
    @students = JSON.parse(result)
  end

  def show
    @student = Student.new
    @metrics = {}
    if params[:id]
      @student.name = params[:id]
      result = Net::HTTP.get(URI.parse('https://crystal-pepsi.herokuapp.com/students/'+ params[:id] + '/meetings'))

      @schedule = JSON.parse(result)
      calculate_metrics
      @metrics

    end

  end

  def calculate_metrics
    all_mins = 0.0
    instr_mins = 0
    @schedule.each do |m|
      if m["tags"].include?("instructional")
        instr_mins += m["duration"]
      end
      all_mins += m["duration"]
    end
    value = instr_mins/all_mins
    @metrics["Percentage of time spent in instructional courses"] = "#{(value * 100).round}%"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Students</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/index.html.erb
<h1>Students</h1>
<ul>
<% @students.each do |student| %>
<li><%= link_to student, student_path(student) %></li>
<% end %>
</ul>

app/views/students/show.html.erb
<h1>Schedule: <%=@student.name %></h1>
<hr>
<ul>
<% @schedule.each do |meeting| %>
<li>Period <%=meeting["period"]%>: <%=meeting["name"] %> (<%= meeting["duration"]%> minutes)
    <% if meeting["tags"].size > 0 %>
        (<%=meeting["tags"].join(",") %>)
    <% end %>
</li>
<% end %>
</ul>

<h1>Metrics</h1>
<ul>
  <% @metrics.each do |k,v| %>
      <li><%=k %>: <%=v %></li>
  <% end %>
</ul>

<hr>
<%= link_to "back", students_path %>